[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "./fruitrunner"
runner = "teleprobe local run --chip nRF52832_xxAA --elf"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
