[unstable]
# enabling these breaks the float tests during linking, with intrinsics
# duplicated between embassy-rp and compilter_builtins
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "teleprobe client run"
#runner = "teleprobe local run --chip RP2040 --elf"

rustflags = [
  # Code-size optimizations.
  "-Z", "trap-unreachable=no",
]

[target.thumbv6m-none-eabi]
runner = 'probe-rs run --chip STM32F091RCTX'

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
